# Generated by Django 4.2.7 on 2025-09-23 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('gender_identity', models.CharField(blank=True, max_length=50)),
                ('pronouns', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('referral_source', models.CharField(blank=True, max_length=200)),
                ('has_gp_referral', models.BooleanField(default=False)),
                ('gp_name', models.CharField(blank=True, max_length=255)),
                ('gp_practice_name', models.CharField(blank=True, max_length=255)),
                ('previous_therapy', models.BooleanField(default=False)),
                ('previous_therapy_details', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('presenting_concerns', models.TextField(blank=True)),
                ('therapy_goals', models.TextField(blank=True)),
                ('consent_to_treatment', models.BooleanField(default=False)),
                ('consent_to_telehealth', models.BooleanField(default=False)),
                ('intake_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('session_number', models.PositiveIntegerField()),
                ('subjective', models.TextField()),
                ('objective', models.TextField()),
                ('assessment', models.TextField()),
                ('plan', models.TextField()),
                ('session_duration', models.PositiveIntegerField(default=50)),
                ('progress_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
                'unique_together': {('patient', 'session_number')},
            },
        ),
    ]
