# Generated by Django 4.2.7 on 2025-09-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patientprofile_progressnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='client_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gp_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gp_provider_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='home_phone',
            field=models.CharField(blank=True, help_text='Home phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_conditions_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medication_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='other_health_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='other_health_professionals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='current_medications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
