# Generated by Django 4.2.7 on 2025-10-07 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patientprofile_client_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Gender identification', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Street address line 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age calculation and healthcare records', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Primary email address for login and communication', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email verification status - required for full system access'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medicare_number',
            field=models.CharField(blank=True, help_text='Medicare number for healthcare billing', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Australian phone number format (+61XXXXXXXXX or 0XXXXXXXXX)', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in Australian format: +61XXXXXXXXX or 0XXXXXXXXX', regex='^\\+?61[0-9]{9}$|^0[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, help_text='Australian postcode (4 digits)', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], help_text='Australian state or territory', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='suburb',
            field=models.CharField(blank=True, help_text='Suburb or city', max_length=100),
        ),
    ]
