# Generated by Django 5.2.7 on 2025-11-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender_alter_user_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='consent_to_data_sharing',
            field=models.BooleanField(default=False, help_text='Consent to share data with third parties (Twilio, Stripe)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_to_data_sharing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_to_marketing',
            field=models.BooleanField(default=False, help_text='Consent to receive marketing communications (APP 7)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_to_marketing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_to_telehealth_date',
            field=models.DateTimeField(blank=True, help_text='Date telehealth consent was given', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_to_telehealth_version',
            field=models.CharField(blank=True, help_text='Version of telehealth consent form', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_to_treatment_date',
            field=models.DateTimeField(blank=True, help_text='Date treatment consent was given', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_to_treatment_version',
            field=models.CharField(blank=True, help_text='Version of consent form accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_withdrawal_reason',
            field=models.TextField(blank=True, help_text='Reason for consent withdrawal'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_withdrawn',
            field=models.BooleanField(default=False, help_text='Patient has withdrawn consent'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='consent_withdrawn_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='parental_consent',
            field=models.BooleanField(default=False, help_text='Parental consent obtained for minor'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='parental_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='parental_consent_name',
            field=models.CharField(blank=True, help_text='Name of parent/guardian giving consent', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='parental_consent_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, help_text='Patient has accepted Privacy Policy'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='privacy_policy_accepted_date',
            field=models.DateTimeField(blank=True, help_text='Date Privacy Policy was accepted', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='privacy_policy_version',
            field=models.CharField(blank=True, help_text='Version of Privacy Policy accepted', max_length=20),
        ),
    ]
