# Generated by Django 5.2.7 on 2025-11-19 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_privacy_consent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when data was soft-deleted/archived', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag - data is archived, not permanently deleted'),
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='Date and time deletion was requested')),
                ('reason', models.TextField(blank=True, help_text="Patient's reason for requesting deletion")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Scheduled for Deletion'), ('rejected', 'Rejected'), ('completed', 'Completed - Data Archived'), ('cancelled', 'Cancelled by Patient')], default='pending', help_text='Current status of the deletion request', max_length=20)),
                ('reviewed_date', models.DateTimeField(blank=True, help_text='Date and time request was reviewed', null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('legal_retention', 'Legal retention period not met (7 years for adults, until 25 for children)'), ('active_appointments', 'Patient has active or upcoming appointments'), ('unpaid_invoices', 'Patient has unpaid invoices'), ('legal_obligation', 'Legal obligation to retain records (court order, investigation)'), ('other', 'Other (specified in notes)')], help_text='Reason for rejection (if rejected)', max_length=50)),
                ('rejection_notes', models.TextField(blank=True, help_text='Additional notes about rejection or approval')),
                ('scheduled_deletion_date', models.DateTimeField(blank=True, help_text='Date when data will be archived/deleted (respects retention policy)', null=True)),
                ('deletion_completed_date', models.DateTimeField(blank=True, help_text='Date when data was actually archived/deleted', null=True)),
                ('retention_period_years', models.PositiveIntegerField(default=7, help_text='Number of years data must be retained (7 for adults, until age 25 for children)')),
                ('earliest_deletion_date', models.DateTimeField(blank=True, help_text='Earliest date data can be deleted based on retention policy', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the deletion request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Patient requesting data deletion', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin or practice manager who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Deletion Request',
                'verbose_name_plural': 'Data Deletion Requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_request',
            field=models.ForeignKey(blank=True, help_text='Reference to the deletion request that triggered this deletion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to='users.datadeletionrequest'),
        ),
    ]
