# Generated by Django 5.2.7 on 2025-11-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_data_deletion_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='telehealth_emergency_acknowledged_date',
            field=models.DateTimeField(blank=True, help_text='Date emergency procedures were acknowledged', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telehealth_emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact for telehealth sessions', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telehealth_emergency_plan',
            field=models.TextField(blank=True, help_text="Patient's plan if telehealth session is interrupted or crisis occurs"),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telehealth_emergency_protocol_acknowledged',
            field=models.BooleanField(default=False, help_text='Patient confirmed understanding of emergency procedures for telehealth sessions'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telehealth_recording_consent',
            field=models.BooleanField(default=False, help_text='Patient consented to telehealth session recording (if applicable)'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telehealth_recording_consent_date',
            field=models.DateTimeField(blank=True, help_text='Date recording consent was given', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telehealth_recording_consent_version',
            field=models.CharField(blank=True, help_text='Version of recording consent accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telehealth_tech_acknowledged_date',
            field=models.DateTimeField(blank=True, help_text='Date technical requirements were acknowledged', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telehealth_tech_requirements_acknowledged',
            field=models.BooleanField(default=False, help_text='Patient confirmed they meet telehealth technical requirements'),
        ),
    ]
