# Generated by Django 5.2.7 on 2025-01-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_telehealth_consent_fields'),
    ]

    operations = [
        # Communication Preferences
        migrations.AddField(
            model_name='patientprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Patient prefers to receive email notifications'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Patient prefers to receive SMS notifications'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='appointment_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Patient prefers to receive appointment reminders'),
        ),
        # Privacy Preferences
        migrations.AddField(
            model_name='patientprofile',
            name='share_progress_with_emergency_contact',
            field=models.BooleanField(default=False, help_text='Patient consents to sharing progress updates with emergency contact'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='share_progress_consent_date',
            field=models.DateTimeField(blank=True, help_text='Date progress sharing consent was given', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='share_progress_consent_version',
            field=models.CharField(blank=True, help_text='Version of progress sharing consent', max_length=20),
        ),
    ]

