# Generated by Django 4.2.7 on 2025-10-20 17:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_appointment_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=20, unique=True)),
                ('service_description', models.CharField(help_text='Description of the service provided', max_length=200)),
                ('service_date', models.DateField(help_text='Date the service was provided')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, help_text='Amount before GST', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_amount', models.DecimalField(decimal_places=2, help_text='GST amount (10% of subtotal)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount including GST', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('medicare_rebate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Medicare rebate amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('out_of_pocket', models.DecimalField(decimal_places=2, help_text='Amount patient pays after Medicare rebate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', help_text='Current invoice status', max_length=20)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('paid_date', models.DateField(blank=True, help_text='Date payment was received', null=True)),
                ('abn', models.CharField(blank=True, help_text='Australian Business Number', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(help_text='Associated appointment', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicareClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(help_text='Unique Medicare claim number', max_length=20, unique=True)),
                ('medicare_number', models.CharField(help_text="Patient's Medicare number", max_length=10)),
                ('service_fee', models.DecimalField(decimal_places=2, help_text='Total service fee charged', max_digits=10)),
                ('medicare_rebate', models.DecimalField(decimal_places=2, help_text='Medicare rebate amount', max_digits=10)),
                ('patient_payment', models.DecimalField(decimal_places=2, help_text='Amount patient pays', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to Medicare'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Current claim status', max_length=20)),
                ('claim_date', models.DateField(help_text='Date claim was submitted')),
                ('processed_date', models.DateField(blank=True, help_text='Date claim was processed by Medicare', null=True)),
                ('medicare_reference', models.CharField(blank=True, help_text='Medicare reference number', max_length=50)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('bulk_billing', models.BooleanField(default=False, help_text='Whether this is a bulk billing claim')),
                ('safety_net_applied', models.BooleanField(default=False, help_text='Whether safety net rebate was applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Associated invoice', on_delete=django.db.models.deletion.CASCADE, related_name='medicare_claims', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Medicare Claim',
                'verbose_name_plural': 'Medicare Claims',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicareItemNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(help_text='Medicare item number (e.g., 80110, 80115)', max_length=10, unique=True)),
                ('description', models.CharField(help_text='Service description', max_length=200)),
                ('service_type', models.CharField(choices=[('psychologist', 'Psychologist'), ('clinical_psychologist', 'Clinical Psychologist'), ('psychiatrist', 'Psychiatrist'), ('gp', 'General Practitioner')], help_text='Type of healthcare provider', max_length=25)),
                ('standard_rebate', models.DecimalField(decimal_places=2, help_text='Standard Medicare rebate amount', max_digits=8)),
                ('safety_net_rebate', models.DecimalField(blank=True, decimal_places=2, help_text='Safety net rebate amount (if applicable)', max_digits=8, null=True)),
                ('min_session_duration', models.PositiveIntegerField(default=50, help_text='Minimum session duration in minutes')),
                ('max_sessions_per_year', models.PositiveIntegerField(default=10, help_text='Maximum sessions per calendar year')),
                ('requires_referral', models.BooleanField(default=True, help_text='Whether a GP referral is required')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item number is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicare Item Number',
                'verbose_name_plural': 'Medicare Item Numbers',
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(help_text='Unique payment identifier', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('medicare', 'Medicare'), ('private_health', 'Private Health Insurance'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], help_text='Method of payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=100)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe charge ID', max_length=100)),
                ('bank_reference', models.CharField(blank=True, help_text='Bank transfer reference', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date payment was processed', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure')),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST amount included in payment', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Associated invoice', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('medicare_claim', models.ForeignKey(blank=True, help_text='Associated Medicare claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.medicareclaim')),
                ('patient', models.ForeignKey(help_text='Patient making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicareclaim',
            name='medicare_item_number',
            field=models.ForeignKey(help_text='Medicare item number for this claim', on_delete=django.db.models.deletion.PROTECT, to='billing.medicareitemnumber'),
        ),
        migrations.AddField(
            model_name='medicareclaim',
            name='patient',
            field=models.ForeignKey(help_text='Patient making the claim', on_delete=django.db.models.deletion.CASCADE, related_name='medicare_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='medicare_item_number',
            field=models.ForeignKey(blank=True, help_text='Medicare item number used', null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.medicareitemnumber'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(help_text='Patient who received the service', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MedicareSafetyNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_year', models.PositiveIntegerField(help_text='Calendar year for safety net tracking')),
                ('total_medical_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total medical expenses for the year', max_digits=10)),
                ('medicare_rebates_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total Medicare rebates received', max_digits=10)),
                ('safety_net_threshold', models.DecimalField(decimal_places=2, default=Decimal('2448.90'), help_text='Safety net threshold amount', max_digits=10)),
                ('is_safety_net_eligible', models.BooleanField(default=False, help_text='Whether patient is eligible for safety net')),
                ('safety_net_date', models.DateField(blank=True, help_text='Date safety net eligibility was reached', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Patient', on_delete=django.db.models.deletion.CASCADE, related_name='safety_net', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicare Safety Net',
                'verbose_name_plural': 'Medicare Safety Nets',
                'ordering': ['-calendar_year'],
                'unique_together': {('patient', 'calendar_year')},
            },
        ),
    ]
