# Generated by Django 4.2.7 on 2025-09-23 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Specialization name (e.g., 'Anxiety Disorders')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the specialization')),
                ('is_active', models.BooleanField(default=True, help_text='Active specialization offered by the clinic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'db_table': 'services_specialization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Service name (e.g., 'Individual Therapy Session')", max_length=200)),
                ('service_type', models.CharField(choices=[('individual', 'Individual Therapy'), ('couples', 'Couples Therapy'), ('family', 'Family Therapy'), ('group', 'Group Therapy'), ('assessment', 'Psychological Assessment'), ('consultation', 'Consultation')], default='individual', max_length=20)),
                ('description', models.TextField(help_text='Detailed service description')),
                ('duration_minutes', models.PositiveIntegerField(default=50, help_text='Session duration in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)])),
                ('standard_fee', models.DecimalField(decimal_places=2, default=180.0, help_text='Standard fee in AUD', max_digits=8)),
                ('medicare_rebate', models.DecimalField(decimal_places=2, default=87.45, help_text='Medicare rebate amount in AUD', max_digits=8)),
                ('medicare_item_number', models.CharField(blank=True, help_text='Medicare item number for billing', max_length=10)),
                ('is_telehealth_available', models.BooleanField(default=True, help_text='Available via video consultation')),
                ('requires_referral', models.BooleanField(default=False, help_text='Requires GP or specialist referral')),
                ('is_active', models.BooleanField(default=True, help_text='Service is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specializations', models.ManyToManyField(blank=True, help_text='Relevant specializations for this service', to='services.specialization')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services_service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahpra_registration_number', models.CharField(help_text='AHPRA registration number', max_length=20, unique=True)),
                ('ahpra_expiry_date', models.DateField(help_text='AHPRA registration expiry date')),
                ('title', models.CharField(choices=[('Dr', 'Dr'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], default='Ms', max_length=10)),
                ('qualifications', models.TextField(help_text='Professional qualifications and certifications')),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of professional experience')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=180.0, help_text='Standard consultation fee in AUD', max_digits=8)),
                ('medicare_provider_number', models.CharField(blank=True, help_text='Medicare provider number for rebates', max_length=15)),
                ('is_accepting_new_patients', models.BooleanField(default=True, help_text='Currently accepting new patients')),
                ('max_patients_per_day', models.PositiveIntegerField(default=8, help_text='Maximum number of patients per day')),
                ('bio', models.TextField(blank=True, help_text='Professional biography for patient portal')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='psychologist_profiles/')),
                ('is_active_practitioner', models.BooleanField(default=True, help_text='Active practitioner status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services_offered', models.ManyToManyField(blank=True, help_text='Services this psychologist provides', to='services.service')),
                ('specializations', models.ManyToManyField(blank=True, help_text='Areas of psychological specialization', to='services.specialization')),
            ],
            options={
                'verbose_name': 'Psychologist Profile',
                'verbose_name_plural': 'Psychologist Profiles',
                'db_table': 'services_psychologist_profile',
            },
        ),
    ]
