# Generated by Django 4.2.7 on 2025-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average patient rating (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='billing_methods',
            field=models.CharField(blank=True, help_text='Billing methods available', max_length=300),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='break_between_sessions_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Break between sessions in minutes'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='currently_active_patients',
            field=models.PositiveIntegerField(default=0, help_text='Currently active patients'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='in_person_available',
            field=models.BooleanField(default=True, help_text='Available for in-person sessions'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='insurance_providers',
            field=models.CharField(blank=True, help_text='Insurance providers accepted (comma-separated)', max_length=300),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='Languages spoken (comma-separated)', max_length=200),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='medicare_rebate_amount',
            field=models.DecimalField(decimal_places=2, default=87.45, help_text='Medicare rebate amount in AUD', max_digits=8),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='personal_website',
            field=models.URLField(blank=True, help_text='Personal or professional website'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='practice_address',
            field=models.TextField(blank=True, help_text='Practice address'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='practice_email',
            field=models.EmailField(blank=True, help_text='Practice email address', max_length=254),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='practice_name',
            field=models.CharField(blank=True, help_text='Name of the practice or clinic', max_length=200),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='practice_phone',
            field=models.CharField(blank=True, help_text='Practice phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='session_duration_minutes',
            field=models.PositiveIntegerField(default=50, help_text='Standard session duration in minutes'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='session_types',
            field=models.CharField(blank=True, help_text='Types of sessions offered (Individual, Couples, Group)', max_length=200),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='sessions_completed',
            field=models.PositiveIntegerField(default=0, help_text='Total sessions completed'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='telehealth_available',
            field=models.BooleanField(default=True, help_text='Available for telehealth sessions'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='total_patients_seen',
            field=models.PositiveIntegerField(default=0, help_text='Total number of patients seen'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='working_hours',
            field=models.CharField(blank=True, help_text="Working hours (e.g., 'Monday-Friday, 9AM-5PM')", max_length=100),
        ),
    ]
