# Generated by Django 4.2.7 on 2025-10-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_psychologistprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Standard end time for work day', null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Standard start time for work day', null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='working_days',
            field=models.CharField(blank=True, help_text='Working days (comma-separated: Monday,Tuesday,Wednesday)', max_length=200),
        ),
    ]
