# Generated by Django 5.2.7 on 2025-11-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_psychologistprofile_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='has_professional_indemnity_insurance',
            field=models.BooleanField(default=False, help_text='Has active Professional Indemnity Insurance'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='insurance_certificate',
            field=models.FileField(blank=True, help_text='Upload insurance certificate (PDF/image)', null=True, upload_to='insurance_certificates/'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='insurance_coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Insurance coverage amount in AUD (e.g., 1000000.00 for $1M)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, help_text='Professional Indemnity Insurance expiry date', null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='insurance_last_verified',
            field=models.DateField(blank=True, help_text='Date insurance certificate was last verified', null=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='insurance_notes',
            field=models.TextField(blank=True, help_text='Additional notes about insurance coverage'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='insurance_policy_number',
            field=models.CharField(blank=True, help_text='Professional Indemnity Insurance policy number', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='insurance_provider_name',
            field=models.CharField(blank=True, help_text='Professional Indemnity Insurance provider name', max_length=200),
        ),
    ]
