# Generated by Django 5.2.7 on 2025-11-12 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, help_text='User email (stored even if user is deleted)', max_length=254, null=True)),
                ('user_role', models.CharField(blank=True, help_text='User role at time of action', max_length=20, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('download', 'Download'), ('export', 'Export')], help_text='Type of action performed', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the object', null=True)),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='What fields changed (before/after values)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/user agent information', null=True)),
                ('request_path', models.CharField(blank=True, help_text='API endpoint or URL accessed', max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE)', max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (error messages, etc.)')),
                ('content_type', models.ForeignKey(blank=True, help_text='Model type (User, Appointment, Invoice, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_timesta_8b04a8_idx'), models.Index(fields=['user', '-timestamp'], name='audit_log_user_id_79f582_idx'), models.Index(fields=['action', '-timestamp'], name='audit_log_action_cf8063_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_log_content_10f046_idx'), models.Index(fields=['user_email'], name='audit_log_user_em_2862cf_idx')],
            },
        ),
    ]
