# Generated by Django 4.2.7 on 2025-10-07 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_psychologistprofile_end_time_and_more'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(help_text='Date and time of the appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of the appointment in minutes'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(help_text='Patient attending the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='psychologist',
            field=models.ForeignKey(help_text='Psychologist conducting the session', on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(help_text='Type of service being provided (therapy, assessment, etc.)', on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', help_text='Current status of the appointment', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='video_room_id',
            field=models.CharField(blank=True, help_text='Twilio video room ID for telehealth sessions', max_length=100),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week for this availability slot'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='end_time',
            field=models.TimeField(help_text='End time of availability (e.g., 17:00)'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether this time slot is currently available for booking'),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='psychologist',
            field=models.ForeignKey(help_text='Psychologist whose availability this represents', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='start_time',
            field=models.TimeField(help_text='Start time of availability (e.g., 09:00)'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='appointment',
            field=models.OneToOneField(blank=True, help_text='Appointment that has booked this time slot', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(help_text='Date of this time slot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(help_text='Exact end time of the slot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether this slot is available for booking'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='psychologist',
            field=models.ForeignKey(help_text='Psychologist whose time slot this is', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(help_text='Exact start time of the slot'),
        ),
    ]
