# Generated by Django 5.2.7 on 2025-01-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_sid', models.CharField(help_text='Twilio recording SID (unique identifier)', max_length=255, unique=True)),
                ('media_uri', models.URLField(help_text='Twilio URL to access the recording')),
                ('media_external_location', models.URLField(blank=True, help_text='External storage location (if applicable)', null=True)),
                ('duration', models.PositiveIntegerField(help_text='Recording duration in seconds')),
                ('size', models.PositiveIntegerField(help_text='Recording file size in bytes')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', help_text='Current status of the recording', max_length=20)),
                ('participant_identity', models.CharField(blank=True, help_text='Participant who was recorded (if applicable)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When recording metadata was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When recording was completed', null=True)),
                ('appointment', models.ForeignKey(help_text='Appointment this recording belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Session Recording',
                'verbose_name_plural': 'Session Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionrecording',
            index=models.Index(fields=['appointment', '-created_at'], name='appointment_appoint_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecording',
            index=models.Index(fields=['recording_sid'], name='appointment_recordi_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecording',
            index=models.Index(fields=['status'], name='appointment_status_idx'),
        ),
    ]

