# Generated by Django 4.2.7 on 2025-10-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(choices=[('telehealth', 'Telehealth'), ('in_person', 'In-Person')], default='telehealth', help_text='Type of session (telehealth or in-person)', max_length=20),
        ),
    ]
