# Generated by Django 5.2.7 on 2025-11-07 21:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resource title', max_length=255)),
                ('description', models.TextField(help_text='Brief description of the resource')),
                ('category', models.CharField(choices=[('anxiety', 'Anxiety'), ('depression', 'Depression'), ('stress', 'Stress Management'), ('sleep', 'Sleep'), ('mindfulness', 'Mindfulness & Meditation'), ('relationships', 'Relationships'), ('self-care', 'Self-Care'), ('grief', 'Grief & Loss'), ('trauma', 'Trauma'), ('addiction', 'Addiction Support')], max_length=50)),
                ('type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('audio', 'Audio/Meditation'), ('guide', 'Guide'), ('worksheet', 'Worksheet/PDF'), ('quiz', 'Quiz/Assessment'), ('infographic', 'Infographic')], max_length=20)),
                ('icon', models.CharField(default='📚', help_text='Emoji icon for display', max_length=10)),
                ('content', models.TextField(blank=True, help_text='Full content (HTML/Markdown)')),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('video_url', 'Video URL'), ('audio_url', 'Audio URL'), ('pdf_url', 'PDF URL')], default='html', max_length=20)),
                ('media_url', models.URLField(blank=True, help_text='URL for video/audio resources', null=True)),
                ('download_url', models.URLField(blank=True, help_text='URL for downloadable files', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail image URL', null=True)),
                ('author', models.CharField(blank=True, help_text='Author name', max_length=255)),
                ('reviewer', models.CharField(blank=True, help_text='Reviewer name', max_length=255)),
                ('last_reviewed_date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(default=list, help_text='List of tags')),
                ('references', models.JSONField(default=list, help_text='List of reference objects')),
                ('duration_minutes', models.PositiveIntegerField(default=10, help_text='Estimated time to complete in minutes')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Total number of views')),
                ('is_published', models.BooleanField(default=True, help_text='Whether resource is published')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured resource')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resources_resource',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='resources_r_categor_8e2710_idx'), models.Index(fields=['type'], name='resources_r_type_ae8095_idx'), models.Index(fields=['is_published'], name='resources_r_is_publ_7afbcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources_bookmark',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='ResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Progress from 0 to 100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_time_seconds', models.PositiveIntegerField(default=0, help_text='Current playback position in seconds')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources_progress',
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='ResourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources_rating',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='ResourceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resources_view',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'resource'], name='resources_v_user_id_467c94_idx')],
            },
        ),
    ]
