# Generated by Django 5.2.7 on 2025-11-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload thumbnail/cover image (JPEG, PNG, etc.)', null=True, upload_to='resources/images/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF file for worksheets, guides, etc.', null=True, upload_to='resources/pdfs/'),
        ),
    ]
